### ISSUE TITLE
SharAI error but cant tell exactly what happened

### ISSUE THREAD

**Issue by louisdeer** [jyoshimi/phil_190_2016#6] opened 2016-03-24 05:07 UTC
![capture](https://cloud.githubusercontent.com/assets/16812759/14008881/7e5a6a96-f143-11e5-9c96-23a3cce3338a.PNG)

**Comment by Insectoid** [comment] 2016-03-24 19:17
Ok, I looked into the code and figured out what the problem is. It should be fixed now. Let me know if you see a problem resurface again

**Closed as completed by Insectoid** 2016-03-24 19:17 UTC
Labels: bug
